name: Validate Files

on:
  push:
    branches:
      - main  # 対象のブランチを指定（例: mainブランチ）

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for invalid file extensions
        run: |
          # Get the list of changed files in the push
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Loop through the changed files and check their extensions
          for FILE in $CHANGED_FILES; do
            if [[ $FILE != *.me && $FILE != LICENSE ]]; then
              echo "❌ Invalid file detected: $FILE"
              exit 1
            fi
          done
          echo "✅ All files are valid."
