name: Validate Files

on:
  push:
    branches:
      - main  # 対象のブランチを指定（例: mainブランチ）

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 全履歴を取得

      - name: Check for invalid file extensions
        run: |
          # Get the list of changed files in the push
          if [[ -z "${{ github.event.before }}" ]]; then
            echo "First push or rebase detected, comparing with initial commit."
            CHANGED_FILES=$(git diff --name-only $(git rev-list --max-parents=0 HEAD) ${{ github.sha }})
          else
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi

          # Loop through the changed files and check their extensions
          for FILE in $CHANGED_FILES; do
            # Skip files in .github/workflows/
            if [[ $FILE == .github/workflows/* ]]; then
              continue
            fi

            # Check for valid files
            if [[ $FILE != *.me && $FILE != LICENSE ]]; then
              echo "❌ Invalid file detected: $FILE"
              exit 1
            fi
          done
          echo "✅ All files are valid."
